// <auto-generated />
using System;
using MACRiverProxy.Auth.Tokens;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MACRiverProxy.Migrations
{
    [DbContext(typeof(TokenKeyStorage))]
    partial class TokenKeyStorageModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.14");

            modelBuilder.Entity("MACRiverProxy.Auth.Tokens.TokenKey", b =>
                {
                    b.Property<string>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpireTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("ActiveTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
