// <auto-generated />
using MACRiverProxy.Auth.LocalAuth;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MACRiverProxy.Migrations.LocalAuthStorageMigrations
{
    [DbContext(typeof(LocalAuthStorage))]
    [Migration("20260525181136_Limit login field length")]
    partial class Limitloginfieldlength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("MACRiverProxy.Auth.LocalAuth.LocalAuthUser", b =>
                {
                    b.Property<string>("Login")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("MACCategory")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MACLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.HasKey("Login");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
